language: java
after_success:
#  - bash <(curl -s https://codecov.io/bash)
  - GRAAL=graalvm-ce-1.0.0-rc13
  - wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc13/$GRAAL-linux-amd64.tar.gz
  - tar -zxf $GRAAL-linux-amd64.tar.gz
  - JAVA_HOME=$PWD/$GRAAL mvn package -Pnative-image