language: java

matrix:
  include:
    - os: osx
      env: PLATFORM=macos-amd64
    - os: linux
      env: PLATFORM=linux-amd64

after_success:
#  - bash <(curl -s https://codecov.io/bash)
  - GRAAL=graalvm-ce-1.0.0-rc13
  - wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc13/$GRAAL-$PLATFORM.tar.gz
  - tar -zxf $GRAAL-$PLATFORM.tar.gz
  - ls -l $GRAAL
  - JAVA_HOME=$PWD/$GRAAL mvn package -Pnative-image
  - mv target/org.netpreserve.jwarc.warctool target/jwarc-$PLATFORM